apiVersion: v1
kind: Pod
metadata:
  name: nginxproxy
  labels:
    app: proxy
spec:
  containers:
  - name: nginxproxy-container
    image: zebra779/nginx-custom:latest
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
